name: 🐛 Package not working
description: Open an issue when a package fails with errors on install or update.
title: "[Bug]: "
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: I have verified that this problem still exists after running `scoop update` AND `scoop update *`
      required: true
- type: input
  attributes:
    label: Package Name
    description: Name of package (install name) which has bug(s)
    placeholder: e.g. duckstation
  validations:
    required: true
- type: textarea
  attributes:
    label: Error message or description of problem
    description: Copy the console log and paste it here.
    render: console
    placeholder: |
      Can't shim 'duckstation-no-gui.exe': File doesn't exist.
  validations:
    required: false
